server:
  tomcat:
    uri-encoding: utf-8

spring:
  servlet:
    multipart:
      maxFileSize: 40MB
      maxRequestSize: 40MB

  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      # 初始化时建立连接的个数
      initial-size: 5
      # 最大连接数量
      max-active: 20
      # 最小连接数量
      min-idle: 5
      # 获取连接等待的超时时间(毫秒)
      max-wait: 60000
      # 获取连接时要不要对该连接进行有效性校验
      test-on-borrow: false
      # 归还连接时要不要对该连接进行有效性校验
      test-on-return: false
      # 是否需要检查空闲的连接有效性
      test-while-idle: true
      # 用来检测连接是否有效的sql
      validation-query: select 1
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 3000
      # 一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 600000
      # 个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000

mybatis:
  #mapper-locations: classpath:mappers/*.xml
  configuration:
      map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true



